# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DeliveredCost
                                 A QGIS plugin
 This plugin provides delivered cost for an area of interest.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-15
        copyright            : (C) 2025 by Tim
        email                : timothy.vandriel@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DeliveredCost class from file DeliveredCost.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .delivered_cost import DeliveredCost
    return DeliveredCost(iface)
