# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DeliveredCostDockWidget
                                 A QGIS plugin
 This plugin provides delivered cost for an area of interest.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tim
        email                : timothy.vandriel@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import (
    QgsProject,
    QgsRasterLayer,
    Qgis,
    QgsMessageLog,
    QgsRectangle,
    QgsVectorLayer,
    QgsFeature,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsGeometry,
    QgsPointXY,
)
from qgis.gui import QgsMapToolPan, QgsVertexMarker
from qgis.utils import iface
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QInputDialog, QApplication
from PyQt5.QtCore import QTimer, Qt
from .draw_polygon_tool import DrawPolygonTool
from .pick_point_tool import PickPointTool

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "delivered_cost_dockwidget_base.ui")
)


class DeliveredCostDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(DeliveredCostDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Manage the OSM layer
        self.osm_layer_id = None
        QgsProject.instance().layerWillBeRemoved.connect(self.on_layer_removed)

        # Background layers
        self.layer_configs = {
            self.esriCheckBox: {
                "name": "ESRI World Imagery",
                "url": "type=xyz&zmin=0&zmax=19&url=https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "provider": "wms",
                "layer_id": None,
            },
            self.burnProbCheckBox: {
                "name": "Burn Probability",
                "url": "url=https://apps.fs.usda.gov/fsgisx03/rest/services/wo_spf_fam/Nat_BurnProbability/ImageServer",
                "provider": "arcgismapserver",
                "layer_id": None,
            },
            self.evtCheckBox: {
                "name": "EVT",
                "url": "url=https://lfps.usgs.gov/arcgis/rest/services/Landfire_LF230/US_230EVT/ImageServer",
                "provider": "arcgismapserver",
                "layer_id": None,
            },
            self.pctCheckBox: {
                "name": "PCL",
                "url": "url=https://apps.fs.usda.gov/fsgisx03/rest/services/wo_spf_fam/Potential_Control_Location/ImageServer",
                "provider": "arcgismapserver",
                "layer_id": None,
            },
        }

        for checkbox in self.layer_configs.keys():
            checkbox.toggled.connect(self.on_layer_checkbox_toggled)

        # Connect sliders to spinboxes
        self.rtSkidderSpeedSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.rtSkidderSpeedSlider, self.rtSpdSpinBox
            )
        )
        self.rtSpdSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.rtSpdSpinBox, self.rtSkidderSpeedSlider
            )
        )
        self.skylineSpeedSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.skylineSpeedSlider, self.skylineSpdSpinBox
            )
        )
        self.skylineSpdSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.skylineSpdSpinBox, self.skylineSpeedSlider
            )
        )
        self.rtSkidderMonSlider.valueChanged.connect(self.rtSkidderMonSpinBox.setValue)
        self.rtSkidderMonSpinBox.valueChanged.connect(
            lambda val: self.rtSkidderMonSlider.setValue(int(val))
        )

        self.skylineMonSlider.valueChanged.connect(self.skylineMonSpinBox.setValue)
        self.skylineMonSpinBox.valueChanged.connect(
            lambda val: self.skylineMonSlider.setValue(int(val))
        )

        self.fellerbuncherRateSlider.valueChanged.connect(
            self.fellerbunchRateSpinBox.setValue
        )
        self.fellerbunchRateSpinBox.valueChanged.connect(
            lambda val: self.fellerbuncherRateSlider.setValue(int(val))
        )

        self.handFellingSlider.valueChanged.connect(
            self.handfellingRateSpinBox.setValue
        )
        self.handfellingRateSpinBox.valueChanged.connect(
            lambda val: self.handFellingSlider.setValue(int(val))
        )

        self.processingSlider.valueChanged.connect(self.processingSpinBox.setValue)
        self.processingSpinBox.valueChanged.connect(
            lambda val: self.processingSlider.setValue(int(val))
        )

        self.haulingSlider.valueChanged.connect(self.haulingSpinBox.setValue)
        self.haulingSpinBox.valueChanged.connect(
            lambda val: self.haulingSlider.setValue(int(val))
        )

        self.handTreatmentSlider.valueChanged.connect(
            self.handTreatmentSpinBox.setValue
        )
        self.handTreatmentSpinBox.valueChanged.connect(
            lambda val: self.handTreatmentSlider.setValue(int(val))
        )

        self.prescribedFireSlider.valueChanged.connect(
            self.prescribedFireSpinBox.setValue
        )
        self.prescribedFireSpinBox.valueChanged.connect(
            lambda val: self.prescribedFireSlider.setValue(int(val))
        )

        self.rtSkidderPayloadSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.rtSkidderPayloadSlider, self.rtSkidderPayloadSpinBox
            )
        )
        self.rtSkidderPayloadSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.rtSkidderPayloadSpinBox, self.rtSkidderPayloadSlider
            )
        )
        self.skylinePayloadSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.skylinePayloadSlider, self.skylinePayloadSpinBox
            )
        )
        self.skylinePayloadSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.skylinePayloadSpinBox, self.skylinePayloadSlider
            )
        )
        self.logTruckPayloadSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.logTruckPayloadSlider, self.logTruckPayloadSpinBox
            )
        )
        self.logTruckPayloadSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.logTruckPayloadSpinBox, self.logTruckPayloadSlider
            )
        )
        # Initialize the draw polygon tool
        self.drawTool = DrawPolygonTool(iface.mapCanvas())
        self.drawTool.polygonCompleted.connect(self.handle_polygon_completed)
        self.drawPolygonButton.clicked.connect(self.activate_draw_tool)

        # Initialize pick point tool
        self.pointTool = PickPointTool(iface.mapCanvas())
        self.pointTool.pointPicked.connect(self.handle_point_picked)
        self.pickPointButton.clicked.connect(self.activate_point_picker)
        self.facility_marker = None

    def update_spinbox_from_slider(self, slider, spinbox):
        spinbox.setValue(slider.value() / 10.0)

    def update_slider_from_spinbox(self, spinbox, slider):
        slider.setValue(int(spinbox.value() * 10))

    def add_osm_basemap(self):
        if getattr(self, "osm_layer_id", None) is None:
            layer_name = "OSM Standard"
            url = "type=xyz&zmin=0&zmax=19&url=http://tile.openstreetmap.org/{z}/{x}/{y}.png"
            layer = QgsRasterLayer(url, layer_name, "wms")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer, addToLegend=False)
                QgsProject.instance().layerTreeRoot().insertLayer(0, layer)
                self.osm_layer_id = (
                    layer.id()
                )  # Store only the layer ID, not the layer object
            else:
                QMessageBox.critical(
                    None,
                    "Layer Load Error",
                    f"Failed to load layer: {layer_name}. Please check the URL.",
                )

    def on_layer_removed(self, layer_id):
        if getattr(self, "osm_layer_id", None) == layer_id:
            self.osm_layer_id = None

    def zoom_to_us_extent_3857(self):
        # Approximate extent for continental U.S. in EPSG:3857 (Web Mercator)
        extent_3857 = QgsRectangle(-14000000, 2800000, -7000000, 6300000)

        # Set extent and refresh canvas
        canvas = iface.mapCanvas()
        canvas.setExtent(extent_3857)
        canvas.refresh()

    def on_layer_checkbox_toggled(self, checked):
        checkbox = self.sender()  # Which checkbox sent this signal?
        config = self.layer_configs.get(checkbox)
        if config is None:
            return

        if checked:
            # Add layer if not already added
            if not config["layer_id"]:
                layer = QgsRasterLayer(
                    config["url"], config["name"], config["provider"]
                )
                if layer.isValid():
                    QgsProject.instance().addMapLayer(layer)
                    config["layer_id"] = layer.id()
                else:
                    QMessageBox.critical(
                        None,
                        "Layer Load Error",
                        f"Failed to load layer: {config['name']}",
                    )
        else:
            # Remove layer if exists
            layer_id = config.get("layer_id")
            if layer_id:
                layer = QgsProject.instance().mapLayer(layer_id)
                if layer:
                    QgsProject.instance().removeMapLayer(layer)
                    iface.mapCanvas().refresh()
                config["layer_id"] = None

    def activate_draw_tool(self):
        # If AOI layer already exists, remove it from project
        if hasattr(self, "aoi_layer_id") and self.aoi_layer_id:
            layer = QgsProject.instance().mapLayer(self.aoi_layer_id)
            if layer:
                QgsProject.instance().removeMapLayer(layer)
            self.aoi_layer_id = None
            iface.mapCanvas().refresh()

        # Set up and activate the drawing tool
        iface.mapCanvas().setMapTool(self.drawTool)

        # Show instructions
        iface.messageBar().pushMessage(
            "Instructions for drawing a polygon",
            "Click to add points, right-click to finish the polygon. AOI will be removed if button is clicked again.",
            level=Qgis.Info,
            duration=25,
        )

    def handle_polygon_completed(self, geom):
        project_crs = QgsProject.instance().crs()
        geom = QgsGeometry(geom)
        self.aoi_geometry = geom

        # Create the layer
        aoi_layer = QgsVectorLayer(
            f"Polygon?crs={project_crs.authid()}", "AOI", "memory"
        )
        QgsProject.instance().addMapLayer(aoi_layer)
        self.aoi_layer_id = aoi_layer.id()  # Store only the ID

        pr = aoi_layer.dataProvider()
        feat = QgsFeature()
        feat.setGeometry(geom)
        pr.addFeatures([feat])
        aoi_layer.updateExtents()
        aoi_layer.triggerRepaint()
        iface.mapCanvas().refresh()

        iface.actionPan().trigger()

    def activate_point_picker(self):
        if self.facility_marker:
            iface.mapCanvas().scene().removeItem(self.facility_marker)
            del self.facility_marker
            self.facility_marker = None
        iface.mapCanvas().setMapTool(self.pointTool)
        iface.messageBar().pushMessage(
            "Instructions for picking a point",
            "Click on the map to pick a point. The point will be marked with a red cross. Press button again to pick a new point.",
            level=Qgis.Info,
            duration=25,
        )

    def handle_point_picked(self, point):
        self.facility_marker = QgsVertexMarker(iface.mapCanvas())
        self.facility_marker.setCenter(point)
        self.facility_marker.setColor(Qt.red)
        self.facility_marker.setIconType(QgsVertexMarker.ICON_CROSS)
        self.facility_marker.setPenWidth(2)
        self.facility_marker.setScale(1)

        self.facility_coords = (point.x(), point.y())
        iface.actionPan().trigger()  # Switch back to pan tool after picking point

    def closeEvent(self, event):
        if hasattr(self, "osm_layer_id") and self.osm_layer_id:
            layer = QgsProject.instance().mapLayer(self.osm_layer_id)
            if layer:
                QgsProject.instance().removeMapLayer(layer)
            self.osm_layer_id = None
        if hasattr(self, "aoi_layer_id") and self.aoi_layer_id:
            layer = QgsProject.instance().mapLayer(self.aoi_layer_id)
            if layer:
                QgsProject.instance().removeMapLayer(layer)
            self.aoi_layer_id = None

        if hasattr(self, "draw_polygon_tool") and self.draw_polygon_tool:
            self.draw_polygon_tool.deactivate()

        if self.facility_marker:
            iface.mapCanvas().scene().removeItem(self.facility_marker)
            del self.facility_marker
            self.facility_marker = None

        # Switch back to pan tool explicitly
        pan_tool = QgsMapToolPan(iface.mapCanvas())
        iface.mapCanvas().setMapTool(pan_tool)
        for config in self.layer_configs.values():
            layer_id = config.get("layer_id")
            if layer_id:
                layer = QgsProject.instance().mapLayer(layer_id)
                if layer:
                    QgsProject.instance().removeMapLayer(layer)
                    iface.mapCanvas().refresh()
                config["layer_id"] = None
            # Uncheck all checkboxes
        for checkbox in self.layer_configs.keys():
            checkbox.setChecked(False)
        self.closingPlugin.emit()
        event.accept()

    def showEvent(self, event):
        """Override showEvent to add OSM layer when the dock widget is shown."""
        if getattr(self, "osm_layer_id", None) is None:
            self.add_osm_basemap()
            QTimer.singleShot(100, self.zoom_to_us_extent_3857)
        super(DeliveredCostDockWidget, self).showEvent(event)
