# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DeliveredCostDockWidget
                                 A QGIS plugin
 This plugin provides delivered cost for an area of interest.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tim
        email                : timothy.vandriel@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "delivered_cost_dockwidget_base.ui")
)


class DeliveredCostDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(DeliveredCostDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Connect sliders to spinboxes
        self.rtSkidderSpeedSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.rtSkidderSpeedSlider, self.rtSpdSpinBox
            )
        )
        self.rtSpdSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.rtSpdSpinBox, self.rtSkidderSpeedSlider
            )
        )
        self.skylineSpeedSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.skylineSpeedSlider, self.skylineSpdSpinBox
            )
        )
        self.skylineSpdSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.skylineSpdSpinBox, self.skylineSpeedSlider
            )
        )
        self.rtSkidderMonSlider.valueChanged.connect(self.rtSkidderMonSpinBox.setValue)
        self.rtSkidderMonSpinBox.valueChanged.connect(self.rtSkidderMonSlider.setValue)
        self.skylineMonSlider.valueChanged.connect(self.skylineMonSpinBox.setValue)
        self.skylineMonSpinBox.valueChanged.connect(self.skylineMonSlider.setValue)
        self.fellerbuncherRateSlider.valueChanged.connect(
            self.fellerbunchRateSpinBox.setValue
        )
        self.fellerbunchRateSpinBox.valueChanged.connect(
            self.fellerbuncherRateSlider.setValue
        )
        self.handFellingSlider.valueChanged.connect(
            self.handfellingRateSpinBox.setValue
        )
        self.handfellingRateSpinBox.valueChanged.connect(
            self.handFellingSlider.setValue
        )
        self.processingSlider.valueChanged.connect(self.processingSpinBox.setValue)
        self.haulingSlider.valueChanged.connect(self.haulingSpinBox.setValue)
        self.haulingSpinBox.valueChanged.connect(self.haulingSlider.setValue)
        self.handTreatmentSlider.valueChanged.connect(
            self.handTreatmentSpinBox.setValue
        )
        self.handTreatmentSpinBox.valueChanged.connect(
            self.handTreatmentSlider.setValue
        )
        self.prescribedFireSlider.valueChanged.connect(
            self.prescribedFireSpinBox.setValue
        )
        self.prescribedFireSpinBox.valueChanged.connect(
            self.prescribedFireSlider.setValue
        )
        self.rtSkidderPayloadSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.rtSkidderPayloadSlider, self.rtSkidderPayloadSpinBox
            )
        )
        self.rtSkidderPayloadSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.rtSkidderPayloadSpinBox, self.rtSkidderPayloadSlider
            )
        )
        self.skylinePayloadSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.skylinePayloadSlider, self.skylinePayloadSpinBox
            )
        )
        self.skylinePayloadSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.skylinePayloadSpinBox, self.skylinePayloadSlider
            )
        )
        self.logTruckPayloadSlider.valueChanged.connect(
            lambda value: self.update_spinbox_from_slider(
                self.logTruckPayloadSlider, self.logTruckPayloadSpinBox
            )
        )
        self.logTruckPayloadSpinBox.valueChanged.connect(
            lambda value: self.update_slider_from_spinbox(
                self.logTruckPayloadSpinBox, self.logTruckPayloadSlider
            )
        )

    def update_spinbox_from_slider(self, slider, spinbox):
        spinbox.setValue(slider.value() / 10.0)

    def update_slider_from_spinbox(self, spinbox, slider):
        slider.setValue(int(spinbox.value() * 10))

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
